# Generated by Django 5.2.1 on 2025-06-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Já existe um usuário com este e-mail.'}, max_length=254, unique=True),
        ),
    ]
